
//Loading into a table using an external stage AWS S3


CREATE STAGE "USDA_NUTRIENT_STDREF"."PUBLIC".MY_S3_BUCKET
URL = 's3://on-demand-files/load/'
CREDENTIALS = (AWS_KEY_ID = 'AKIAUVWFWKATA4AHVFMT' AWS_SECRET_KEY = '****************************************');

LIST @MY_S3_BUCKET


CREATE TABLE WEIGHT_INGEST (
    NDB_NO	VARCHAR(7)
    ,SEQ	VARCHAR(4)
    ,AMOUNT	NUMBER(6,3)
    ,MSRE_DESC	VARCHAR(86)
    ,GM_WGT	NUMBER(7,1)
    ,NUM_DATA_PTS	NUMBER(4,0)
    ,STD_DEV	NUMBER(7,3)
  )



COPY INTO WEIGHT_INGEST
FROM @MY_S3_BUCKET
FILES = ('WEIGHT.txt')
FILE_FORMAT = (FORMAT_NAME = USDA_FILE_FORMAT);



//Transforming data

CREATE OR REPLACE TABLE WEIGHT (
    NDB_NO	VARCHAR(5)
    ,SEQ	VARCHAR(2)
    ,AMOUNT	NUMBER(6,3)
    ,MSRE_DESC	VARCHAR(84)
    ,GM_WGT	NUMBER(7,1)
    ,NUM_DATA_PTS	NUMBER(4,0)
    ,STD_DEV	NUMBER(7,3)
  );


INSERT INTO WEIGHT(
SELECT
    REPLACE(NDB_NO,'~') as NDB_NO
    ,REPLACE(SEQ,'~') as SEQ
    ,AMOUNT
    ,REPLACE(MSRE_DESC,'~') as MSRE_DESC
    ,GM_WGT
    ,NUM_DATA_PTS
    ,STD_DEV
FROM WEIGHT_INGEST);



//Transforming another example

create table LANGDESC
(FACTOR_CODE VARCHAR(5), DESCRIPTION VARCHAR(140));


SELECT $1, $2 FROM @MY_S3_BUCKET/LANGDESC.txt;


COPY INTO LANGDESC
FROM  (SELECT REPLACE($1,'~'), REPLACE($2,'~') FROM @MY_S3_BUCKET/LANGDESC.txt)
FILE_FORMAT = USDA_FILE_FORMAT;


SELECT * FROM LANGDESC;

