
//Loading into a table using a local file

CREATE DATABASE USDA_NUTRIENT_STDREF
COMMENT = 'My nutrition database';


CREATE TABLE FD_GROUP_INGEST
(FDGRP_CD VARCHAR(6), FDGRP_DESC VARCHAR(62));


CREATE FILE FORMAT "USDA_NUTRIENT_STDREF"."PUBLIC".USDA_FILE_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = '^';


PUT file://<file_path>/FD_GROUP.txt @FD_GROUP_INGEST/ui1620717737839

COPY INTO "USDA_NUTRIENT_STDREF"."PUBLIC"."FD_GROUP_INGEST"
FROM @/ui1620717737839
FILE_FORMAT = '"USDA_NUTRIENT_STDREF"."PUBLIC"."USDA_FILE_FORMAT"'
ON_ERROR = 'ABORT_STATEMENT'
PURGE = TRUE;
