
//Creating Outbound Share

//LAB 3 - EXERCISE 1 -----------------------------------;



-- Converting Regular views to secure view

ALTER VIEW "INTL_DB"."PUBLIC"."NATIONS_SAMPLE_PLUS_ISO"
SET SECURE;

ALTER VIEW "INTL_DB"."PUBLIC"."SIMPLE_CURRENCY"
SET SECURE;



--Creating Outbound Shares by adding table and secure views.

CREATE SHARE "INTL_SHARE" COMMENT='';
GRANT USAGE ON DATABASE "INTL_DB" TO SHARE "INTL_SHARE";
GRANT USAGE ON SCHEMA "INTL_DB"."PUBLIC" TO SHARE "INTL_SHARE";
GRANT SELECT ON VIEW "INTL_DB"."PUBLIC"."COUNTRY_CODE_TO_CURRENCY_CODE" TO SHARE "INTL_SHARE";
GRANT SELECT ON VIEW "INTL_DB"."PUBLIC"."CURRENCIES" TO SHARE "INTL_SHARE";
GRANT SELECT ON VIEW "INTL_DB"."PUBLIC"."INT_STDS_ORG_3661" TO SHARE "INTL_SHARE";
GRANT SELECT ON VIEW "INTL_DB"."PUBLIC"."SIMPLE_CURRENCY" TO SHARE "INTL_SHARE";

--Check the share

USE ROLE ACCOUNTADMIN;

DESC SHARE INTL_SHARE;